// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMSvB8v74xaIADiQHqImDHm76g751Dz_c',
    appId: '1:552928492469:android:1ab3c221f39f056281b7fc',
    messagingSenderId: '552928492469',
    projectId: 'e-roll-8270a',
    storageBucket: 'e-roll-8270a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9KRsdbUnLoiX-0fX5shT9Z2BSh1cxFSQ',
    appId: '1:552928492469:ios:a2448989fc0f63d781b7fc',
    messagingSenderId: '552928492469',
    projectId: 'e-roll-8270a',
    storageBucket: 'e-roll-8270a.firebasestorage.app',
    iosBundleId: 'com.example.eroll',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQAjE_-JQiTlZsWl4wMHDu8ojRj_uEsw',
    appId: '1:552928492469:web:aff180e3a560dd3f81b7fc',
    messagingSenderId: '552928492469',
    projectId: 'e-roll-8270a',
    authDomain: 'e-roll-8270a.firebaseapp.com',
    storageBucket: 'e-roll-8270a.firebasestorage.app',
    measurementId: 'G-P86BY4WBZC',
  );

}